### ISSUE TITLE
Required Control: No. 16, AU-6, Audit Review, Analysis, and Reporting

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#100]

**Comment by rgaitonde** [comment]
All of the AU-6 controls should be required without strong audit logs and controls after an incident it will be difficult to determine what happened.

**Comment by FedRAMP** [comment]
Thank you for your suggestion. We used the NIST SP 800-53 Revision 4 baseline for low systems as a
 starting point. While AU-6 is designated by NIST for low systems, the AU-6 enhancements are not. There are many controls excluded by NIST for low, and we are electing to follow that baseline unless we are presented with a compelling reason to add a non-low requirement for low systems. An AO always has the latitude to add this or any requirement as appropriate.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
