### ISSUE TITLE
Step 1 - Question 6: Is the cloud service hosted within a FedRAMP Authorized infrastructure?

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#108]

**Comment by ultrashea** [comment]
Are there provisions to ensure that a Tailored service is segregated from higher impact systems that may be hosted within the same infrastructure?  (i.e., to prevent an attacker who compromises a Tailored service from using said service to pivot to higher impact system)

(This may be at least partially addressed by SC-7, but more explicit requirements/documentation re: this would be a good idea)

**Comment by steveohsteveoh** [comment]
agree this should be more explicit particularly if the vendor is self-attesting but would add that the SSP should clearly define the boundary and services within that boundary

**Comment by JuniperChad** [comment]
I believe the question which should be asked is: In choosing a service which is hosted in a authorized cloud, which cloud is best for me (between commercial, FedRAMP Moderate, and FedRAMP High). I have seen end users who will default to FedRAMP High because they think level 4-5 Cloud will be the most secure for them, which is great for DOD Intel, but not HIPAA...

**Comment by edward-mcclure** [comment]
By "infrastructure" in this context, do we mean IaaS, PaaS, PaaS+IaaS, or something else entirely? By "FedRAMP Authorized" do we include agency authorization? Are agencies permitted to authorize PaaS and IaaS?

**Comment by FedRAMP** [comment]
Thank you for your comment. The concern for separating higher-impact systems within the cloud is valid. Higher-impact systems could only exist within the cloud platform if the underlying service provider received an authorization at that higher level. In that case, its ability to keep each SaaS instance separate would have been assessed and its ability to perform higher sensitivity separation protection would exist at that higher level.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
