### ISSUE TITLE
LISaaS Requirements

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#115]

**Comment by eric2525** [comment]
The FedRAMP Tailored controls selected - are these based on the previous FedRAMP Critical Controls? Or do these have a different bases since only targeting a low system categorization level?

**Comment by collabarchitect** [comment]
Kindly see my comment on #109, thanks!

**Comment by artdeane** [comment]
For "conditional" requirements, what is the determining factor? What determines if a conditional requirement is actually required?

**Comment by FedRAMP** [comment]
Thank you for your comment. Conditional requirements are explained in APPENDIX A - FedRAMP Tailored Security Controls Baseline. The controls were selected from the list of NIST 800-53 controls for Low systems. FedRAMP identified those controls that are typically satisfied by an underlying service provider and those typically satisfied by the government directly. We are not waiving these controls. We are identifying controls for which to say the CSP is not typically responsible with an LI-SaaS. This allows the CSP to focus only on the controls for which they are responsible.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
