### ISSUE TITLE
Purpose

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#117]

**Comment by katielewin** [comment]
The Purpose statement contains very brief guidance on the responsibility of the official who grants the ATO to ensure that the number of controls in the cert as sufficient for the risk.  Add more detail on the reference in FISMA 800.53 rev4 and perhaps some guidelines to evaluate when to add additional controls.

**Comment by druboi31779** [comment]
Additionally recommend making it very clear that this is intended for agency use ONLY. Not to be used as a JAB-provisional type ATO that can be leveraged at multiple agencies. This is agency by agency (which seems to align with having the option to use an independent assessor, 3PAO, or the agency itself to assess the system prior to authorization). I felt that I had to search for that language (found in second sentence, third paragraph of the "Purpose" section). Should be explicitly stated, in my opinion.

**Comment by jbjonesjr** [comment]
_Hi! I work for GitHub, but I also did Govt IT for over a decade prior. These comments are in my personal capacity_

For agencies who choose to reuse portions of another agencies Tailored ATO, is there a defined process for this?

**Comment by FedRAMP** [comment]
Thank you for your comment. While we agree agency AOs may require additional guidance, we will add that guidance external to these documents for now and may include later if appropriate. We agree with the need to clarify FedRAMP Tailored is only for FedRAMP Agency ATOs. The final documentation will clarify this.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
