### ISSUE TITLE
General Policy

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#118]

**Comment by JTRFedRAMPHHS** [comment]
Requested action - further clarification on self attestation:

•	In FedRAMP tailored, there are a set of controls that only require self-attestation on behalf of the CSP. HHS was unsure of the level of documentation required for these controls. 
o	Does the CSP only attest that the controls are in place? 
o	How does the CSP formally submit the self-attestation? Is there a single document where they sign off to self-attest?
o	 Does the CSP still need to document their implementation in the SSP but simply does not test their implementation?
o	HHS also has a concern about the level of risk acceptance need to  ATO an system that, where the CSP is allow to self-attest to the implementation and ongoing operation of a  fairly large subset of controls.

**Comment by katielewin** [comment]
FedR Tailored is a much needed addition to the FedRAMP methodology.  Addresses the issues of "costs too much, takes too much time"  
Use a text box convention to add examples or clarifying examples.  Many agencies and CSPs have questions about how to start and how processes/requirements apply to specific stakeholders

**Comment by ssanborn** [comment]
What would the difference be between "low risk" and "moderate" on the FedRAMP dashboard and how would that define a cloud solution when agencies are viewing their options?

**Comment by pamcarpenterva** [comment]
The fed ramp office needs to provide on line training for industry and agencies for FedRamp Tailored.....

**Comment by anrandal** [comment]
The policy needs to provide specific guidance on the inheritance model for a SaaS that is running on FedRAMP Authorized PaaS.

**Comment by jgraf1** [comment]
Recommend CSPs are identified within the FedRAMP Marketplace as having followed the FedRAMP tailored process

**Comment by pamcarpenterva** [comment]
For the controls requiring only self attestation, it is recommended that the cloud solution be able to provide their own documentation to attest to the control as opposed to requiring a 3PAO attesting to the control.  This will allow the solution provider to decide whether they employ a 3PAO or not.

**Comment by stephenjcaruso** [comment]
limited number of controls finally driving toward a practicable baseline, which agencies can augment with additional controls.

**Comment by JBitzer** [comment]
documentation - when to be made available - the appendixes which indicate "in process" - rather hard to determine how easy or hard to accomplish
if purpose of Tailored is to facilitate and to accelerate - need to know how much of this is repeatable, re-useable - our folks can't comment on what is missing or hard

**Comment by stephenjcaruso** [comment]
would be interested in seeing how agencies plan to leverage this new policy to identify and approve LISaaS already in use...  specific processes, best practices, etc.

**Comment by marthaakalu** [comment]
In the 6-step RMF process, when will we interact with Fedramp, what types of interaction, how long will it take (e.g., to obtain approval), and where is it documented?

**Comment by steveohsteveoh** [comment]
Would it make sense that FedRAMP Tailored would allow a TIC waiver due to the data classification?

**Comment by pamcarpenterva** [comment]
Would recommend that the FedRamp office have a listing of solutions that are FedRamp Tailored on the fedRamp site as you do today with FedRamp Authorized, FedRamp Ready, etc.

**Comment by arcbeckman** [comment]
How is open source software integrated into the baseline (ex: Apache)? How do the controls apply?

**Comment by stephenjcaruso** [comment]
The policy could use further clarification on the role of the 3PAO in the LISaaS use case. In conversation with the FedRAMP PMO, we just learned that a 3PAO is not required, but that was not completely obvious from the draft text. This is a highlight for both CSPs and agencies.

**Comment by FedRAMP** [comment]
Thank you for your comments. The controls are still documented in APPENDIX B - FedRAMP Tailored LI-SaaS Template, which serves as the System Security Plan (SSP), Security Assessment Plan (SAP) and Security Awareness Report (SAR). The attestation language has been enhanced to include specific attestation statements. These can be reviewed in APPENDIX E - FedRAMP Tailored LI-SaaS Self-Attestation Requirements. Appendices B and E are submitted as part of the authorization.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release

**Comment by mudakala** [comment]
Any updates on this question - Would it make sense that FedRAMP Tailored would allow a TIC waiver due to the data classification

**Comment by cbukovac** [comment]
@mudakala TIC is only appropriate for the transmission of sensitive information and LI-SaaS must not have any sensitive information in it. Since the two are mutually exclusive, FedRAMP believes a waiver is not necessary. If there is a scenario where an LI-SaaS requires TIC connectivity, we would need to evaluate that on a case-by-case basis. If you have any additional questions on this, please feel free to reach out to info@fedramp.gov. Thanks!
