### ISSUE TITLE
Privacy Information

### ISSUE THREAD

**Issue by Kaiiz** [GSA/fedramp-tailored#122]
I see questions related to Privacy or Personally Identifiable Information (PII) as related to its use in the LISaaS Solution. 

I have found some information describes  PII and how to Categorize PII.

The documents are located at CSRC.NIST.GOV and they are...
- NIST SP 800-53 , Appendix J (Privacy Control Catalog), specifically referring to control AR-2
-NIST SP 800-122, "Guide to Protecting the Confidentiality of Personally Identifiable Information"

There is also a document that contains information on "Privacy Threshold Analysis and Assessment" located at ..
https://www.opm.gov/information-management/privacy-policy/privacy-references/piaguide.pdf

**Comment by collabarchitect** [comment]
NOTE: This comment may need to be moved under #110. Thanks.

So thank you for the references! 

My questions: 
1. Who determines which PII does / does not fit into the Categorization?
2. Does PII automatically disqualify a system from using FedRAMP Tailored?
3. Would a flow-chart process help better describe the decision making needed?
4. Will Categorization be exclusive to 'types of CSP domains" (e.g. AWS Commercial vs. AWS GovCloud, etc.)

**Comment by rgaitonde** [comment]
PII should be determined by the agency based upon FIPS 199

**Comment by JTRFedRAMPHHS** [comment]
At least at HHS PII would automatically raise the risk impact level to a moderate.

The domain to access the service may be similar, but I think you would need to ensure that the service is separate.

**Comment by Wynsome** [comment]
In response to Collabarchitect Question 1. PII should be determined by the information owner. I believe it should be addressed during the initial review of CSP/CSO by agencies. If it is determined that the agency information/data will include PII then the tailoring for PII should take place then and the related privacy controls get "tailored" to the SSP package. Compliance for PII/PHI should be address in SLA/Contract

**Comment by Wynsome** [comment]
JTRFedRAMPHHS can you elaborate?

**Comment by HHS-DVP** [comment]
@collabarchitect 1: The CSP should determine (based on NIST 800-60 information types) what qualifies as PII, and what the FIPS 199 will be after that.

2: PII automatically makes the categorization moderate, so yes, it would disqualify that service. 

3: Its possible, but I think if you are familiar with the NIST documents, it would just be restating what you already know. 

4: No, but it is definitely geared towards SaaS.

**Comment by collabarchitect** [comment]
If each Agency determines their own PII, how do we as Vendors categorize if the information we have in our SaaS is or is not PII and if or not it mandates Moderate-level Controls?

**Comment by Kaiiz** [comment]
I am curious if controls could be added bumping Confidentiality for Privacy / PII up to Moderate
 and then utilized in the LISaaS offering?

**Comment by Kaiiz** [comment]
Like Access Controls or Encryption enhancements?

**Comment by Kaiiz** [comment]
Or could FedRamp add tailoring controls to the low Confidentiality baseline to specifically include PII in the offering? A possible Overlay for Agencies that have PII ??

**Comment by JTRFedRAMPHHS** [comment]
@Wynsome For example, a CSP could offer multiple services from a portal with a single domain cloudtool.com - but once inside the portal you would need to make sure that the actual service offered would be separate from low/moderate offerings.

**Comment by FedRAMP** [comment]
Thank you for your comment. There was overwhelming feedback regarding a threshold for PII. We have defined a PII allowance for systems that collect only enough PII to provide a login capability. While FedRAMP is asserting a system may be considered low with only this threshold of PII, each agency's Authorizing Official (AO) will always have the final decision.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
