### ISSUE TITLE
Fedramp tailored

### ISSUE THREAD

**Issue by DavidPalmer2017** [GSA/fedramp-tailored#124]
Flexibility!

**Comment by RWCIT** [comment]
From a first look, there isn't anything that struck me as a "hot button" to gripe about.  That seems like a pretty good starting point.  I'll probably add a vote to a couple of the PII comments.

**Comment by marthaakalu** [comment]
Is Fedramp tailored consistent with the NIST 800-53r4 security controls for a Low category system? Many controls are missing for that category. Can you clarify the difference?

**Comment by Kaiiz** [comment]
In response to your question Marthaakalu, I believe the initial baseline of controls for LOW are utilized from NIST 800-53 R4. Then Fed Ramp tailors the baseline to accommodate Cloud Computing. (In cloud computing the custodian of the data is the cloud vendor, therefore controls are dispersed differently than if the categorization was with a Govt Data Center)

**Comment by FedRAMP** [comment]
Thank you for your comments. Yes, FedRAMP Tailored is consistent with NIST 800-53r4. It is intended specifically for LI-SaaS to leverage existing IaaS or PaaS. We focus only on those requirements that would typically apply to the SaaS in that scenario and pre-filter those that are typically either inherited from the leveraged provider or addressed by the government.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
