### ISSUE TITLE
POA&M Control CA-5

### ISSUE THREAD

**Issue by JTRFedRAMPHHS** [GSA/fedramp-tailored#125]
•	Why does FedRAMP tailored allow for self-attestation for the creation of a POA&M (CA-5)? The CSP could simply provide the POA&M as proof. 
o	Does this mean that the CSP going through the FedRAMP tailored process is not required to maintain a POA&M for continuous monitoring?

**Comment by stephenkovac** [comment]
Without a POA&M how do you track open issues or past issues?

**Comment by FedRAMP** [comment]
Thank you for your comment. Self-attestation is about eliminating the need for the assessor to verify the requirement. APPENDIX D - FedRAMP Tailored LI-SaaS Continuous Monitoring Guide still requires monthly reporting. As this reporting will be monitored by the government, and as we are not requiring a particular POA&M format for LI-SaaS, we believe there is no need for the assessor to also assess this.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
