### ISSUE TITLE
Potential for Mis-Construed Pricing

### ISSUE THREAD

**Issue by MariaHorton** [GSA/fedramp-tailored#126]
There has been some discussion on whether the Tailored Baseline which is 1/3 of the controls is 1/3 of the price.   There is some potential that the linear thinking may create false impressions.  There is still a review of the attestations that needs to be accomplished.

**Comment by JTRFedRAMPHHS** [comment]
I still think a reduced baseline would provide a lower price for the assessment. It may not by exactly 1/3, but the business has to be ready to take on these costs to do business with the Government.

**Comment by jbjonesjr** [comment]
_Hi! I work for GitHub, but I also did Govt IT for over a decade prior. These comments are in my personal capacity_

> but the business has to be ready to take on these costs to do business with the Government.

Not to dig into the specifics about how much cost savings this will provide over previous FedRAMP controls, but I would draw attention to the last statement.

From everything I've read and heard, one of the goals is to make it easier for the Government to procure cloud services. From the introduction:

> we can continue to provide the government with the agility to leverage valuable industry services while maintaining the appropriate level of security.

I read that as providing the Government a chance to more easily procure industry services, not the other way around.

**Comment by seanru** [comment]
The reality from the ground (from my albeit limited perspective) is FedRAMP has made it more difficult and more complicated from a contracting and security standpoint. We're hoping that FedRAMP tailored or FedRAMP accelerated can provide a solution.

**Comment by FedRAMP** [comment]
Thank you for your comment. At this time, FedRAMP has no real-world information to quantify actual cost savings associated with FedRAMP Tailored. As agencies and Cloud Service Providers (CSP) adopt Tailored for Low Impact-Software as a Service (LI-SaaS), we will capture costs. When we have enough cost information to quantify specific savings, we will share those estimates.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
