### ISSUE TITLE
PL-2(3) System Security Plan/Cordinate with Other Organization

### ISSUE THREAD

**Issue by doc-fuller** [GSA/fedramp-tailored#127]
This should be required not attested to by CSP.

**Comment by minime1022** [comment]
@doc-fuller Could you provide rationale for requiring the control?

**Comment by MariaHorton** [comment]
I would want to see evidence cited if self attested or see evidence if a 3PAO accomplishes this.  Many organizations do not coordinate or provide governance to their third party support.

**Comment by doc-fuller** [comment]
The PL-2 control is required but the PL-2(3) is identified as attested. Who is responsible party for the SSP the CSP or the AO who approves. NIST 800-53 indicates the AO is responsible but can't take responsibility for attestation from CSP.

**Comment by FedRAMP** [comment]
Thank you for your suggestion. We used the NIST SP 800-53 Revision 4 baseline for Low systems as a starting point. While PL-2 is designated by NIST for Low systems, PL-2 (3) is not. There are many controls excluded by NIST for Low, and we are electing to follow that baseline unless we are presented with a compelling reason to add a non-Low requirement for Low systems. An AO always has the latitude to add this or any requirement as appropriate.

In general an AO is always authorizing a system based on a belief the system has an acceptable security posture for its sensitivity level. That belief is based on the extent/accuracy of an assessment and the level of trust in that assessment. An AO has the authority to accept an attestation from a CSP or to require further assessment. Thank you all for your input and participation

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
