### ISSUE TITLE
Citizenship

### ISSUE THREAD

**Issue by lcore** [GSA/fedramp-tailored#130]
Would be good to have clarity on up-front requirements about US Citizenship. That may be a blocker for some companies, even though the "real" FedRAMP tailored requirements can be met.  Is it possible to say that any agency that is ok with FedRAMP tailored can't have additional US Citizen requirements?

**Comment by FedRAMP** [comment]
Thank you for your question. As with all FedRAMP authorizations, FedRAMP Tailored does not specify a citizenship requirement as there is no government-wide requirement on citizenship. The only requirement is for the CSP to perform background checks, and the CSP has the freedom to determine exactly what background checks are performed. While a CSP may have non-US persons supporting their system and can still achieve an ATO with some agencies, there are several agencies that maintain their own citizenship requirements. In other words, a CSP using non-US persons is still FedRAMP compliant, but will find their market limited among Federal agencies.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
