### ISSUE TITLE
Frequency of POA&M reviews

### ISSUE THREAD

**Issue by lcore** [GSA/fedramp-tailored#131]
It would be good to set a standard requirement about the min/max required frequency for POA&M updates with agencies.  If an agency can require updates monthly vs. quarterly, it could significantly impact the level of effort on the company's side, and therefore the decision to go or no-go.  If we are talking about low-risk data, then perhaps we need to set requirements on the agency-end that enforces response to any issues be commensurate with the "low risk" nature of the data (i.e. not needing frequent and in-depth reviews of POA&Ms).

**Comment by FedRAMP** [comment]
Thank you for your comment. The FedRAMP Tailored revision includes a complete Appendix D - FedRAMP Tailored LI-SaaS Continuous Monitoring Guide, which specifies monthly reporting; however, an individual agency's AO has the authority to specify a different reporting frequency if the AO believes it is appropriate.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
