### ISSUE TITLE
General 

### ISSUE THREAD

**Issue by monetter** [GSA/fedramp-tailored#134]
What are the "next steps" for FedRAMP Tailored? 
- Will the responses to the comments and questions be posted for public review?  
- When will the next release of FedRAMP Tailored be posted for public comment?
- What is the anticipated timeframe that FedRAMP Tailored will be final and available for agencies?

**Comment by FedRAMP** [comment]
Thank you for your questions. We are publishing the updated documents and responses to comments now with a public comment period from July 13 to July 27. Depending on the comments we receive during the second comment period, we expect to have FedRAMP Tailored finalized and available for agencies by September 1st, 2017. Thank you for your participation!

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
