### ISSUE TITLE
Re: Hi Evan

### ISSUE THREAD

**Issue by katielotterman** [GSA/fedramp-tailored#135]
I looked at some of the questions on GitHub and I see a lot of questions revolving around low, low, low baseline.

To clarify exactly what FedRamp did to arrive at LISaas you may want to first provide the definition of a low, low, low baseline as Defined in FIPS 199 =

The potential impact is LOW if— − 
The loss of confidentiality, integrity, or availability could be expected to have a limited adverse effect on organizational operations, organizational assets, or individuals.

AMPLIFICATION: A limited adverse effect means that, for example, the loss of confidentiality, integrity, or availability might: (i) cause a degradation in mission capability to an extent and duration that the organization is able to perform its primary functions, but the effectiveness of the functions is noticeably reduced; (ii) result in minor damage to organizational assets; (iii) result in minor financial loss; or (iv) result in minor harm to individuals.

then,

Tailored to FedRamp Cloud Specifications for arriving at a LISaaS Solution.

Thanks,

Bill K

**Comment by FedRAMP** [comment]
Thank you for the great clarification as well as the amplification statement. We intend to use it in training materials or other guidance.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
