### ISSUE TITLE
FedRAMP Tailored

### ISSUE THREAD

**Issue by katielotterman** [GSA/fedramp-tailored#136]
I just read an article on the FedRAMP Tailored initiative and was wondering if you needed a test case. Our Innoslate(R) software meets the 6 proposed criteria now and is available on all the major cloud providers (Amazon, Microsoft, and Google), as well as on a number of classified systems. We could also use Innoslate(R) to model and capture data on the process, thus giving your organization an explicit case study.

If you are interested, please contact me at the numbers below. 
Thanks, 
Steve Dam

**Comment by FedRAMP** [comment]
Thank you for your offer. FedRAMP Tailored is intended for systems that already have agency customers. If you have agency customers and believe your system meets all the criteria, please work with your Agency's points of contact to approach FedRAMP.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
