### ISSUE TITLE
Fwd: Question for: FedRAMP Tailored Comment-a-thon

### ISSUE THREAD

**Issue by katielotterman** [GSA/fedramp-tailored#137]
Hi Evan,

During the Q&A at the end of the Draft Security Requirements for the Low-Impact SaaS FedRAMP Tailored Baseline, the presenter indicated that for some fed gov services provided to customers, some PII is voluntarily submitted in order for the service to be provided and there was an implication that an SaaS collecting such PII might still be considered a candidate for FedRAMP Tailored under certain circumstances.

Here is a perfect example of such a service that the fed gov library community has the technological capability of providing, but is barred from doing so because of the PII consideration:

The public portal providing search and view access to our library catalogs (which, themselves, are not 'mission critical' and consist of no sensitive data -- even though they are 'enterprise systems') does not require login, however, additional features are enabled if one has a 'patron account' for this portal, that is set up either via self-registration webform or via request to the librarian.

A 'My Account' option such as described above requires a Patron Record that could be limited to the email address only, but this would have to be captured in order to provide the service, a service which is entirely voluntary, at the request of the benefiting individual -- benefits include:

a.) ability to save searches and rerun them 
b.) ability to create a permalink for a saved search and share it 
c.) ability to save selected search results to a list 
d.) ability to create a permalink for the search results and share it 
e.) ability to set up an RSS manager 
f.) ability to submit requests for reference assistance and track progress on request fulfillment

You get the picture.

Fed Gov librarians are, for now, not enabling these features provided via our SaaS library systems, because to do so would mean that we'd fall into the category of a Federal System of Records and would have to post a System of Records Notification (SORN) in the Federal Register, etc.

As a result, our customers (including staff in our organizations and other fed gov agencies who use the 'public' portal for research -- the 'staff' portal is only for our library cataloging personnel and sysadmins) are denied very rich services that support their job functions, plus the librarians lose significant efficiencies (e.g., we have to deal with reference questions via simple email processes).

Thanks!

Cheers,

Amalin

**Comment by FedRAMP** [comment]
Thank you for your comment. There was overwhelming feedback regarding a threshold for PII. We have defined a PII allowance for systems that collect only enough PII to provide a login capability. While FedRAMP is asserting a system may be considered low with only this threshold of PII, each agency's AO will always have the final decision.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
