### ISSUE TITLE
Comments on Proposed FedRAMP Tailored

### ISSUE THREAD

**Issue by katielotterman** [GSA/fedramp-tailored#140]
Comments from Karen Petraska
[FedRAMP tailored comments (1).docx](https://github.com/GSA/fedramp-tailored/files/959710/FedRAMP.tailored.comments.1.docx)

**Comment by FedRAMP** [comment]
Thank you for your comment. The FedRAMP Low baseline applies to all cloud systems seeking authorization for FIPS-199 Low sensitivity. This includes SaaS, PaaS and IaaS; and includes all appropriate NIST 800-53, Rev 4 controls regardless of whether they are implemented by the CSP, underlying service provider, or the government.

FedRAMP Tailored is strictly for SaaS implementations residing on an existing PaaS or IaaS. Further, tailored identifies those controls that are typically inherited form the underlying provider and those typically implemented by the government, allowing the CSP for the LI-SaaS to focus only on those controls related to their system. FedRAMP Tailored also prioritizes this subset of controls. While all are still required, only the most critical are assessed.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
