### ISSUE TITLE
USAID Feedback on FedRAMP Tailored Baseline

### ISSUE THREAD

**Issue by katielotterman** [GSA/fedramp-tailored#143]
I hope it is not too late to provide feeback on the FedRAMP tailored baseline. Below you will find USAID's comments:

What is the difference between FedRAmp Low Baseline and Low-Impact Software-as-a-Service (LISaaS) Cloud Services? Specifically what is the control count for (LISAAS) v FedRamp Low (xxx) controls count?

To be considered a FedRAMP Tailored LISaaS cloud service, CSP has to answer yes to six questions. This is not enough to qualify a system to be a considered for LISSA, this enough to be considered FEDRAMP low. Need to define the consideration requirement more clearly, otherwise all FedRamp low will be qualified for the tailored service.

What specific guidance allows FEDRAMP to bypass the FIPS-200 minimum security requirement? Has this been vetted with the OIG? What is the OIG stance on Agencies not meeting minimum security requirements and following a tailored approach requiring CSP less security controls than the minimum requirement.

What is the difference between FedRamp Tailored- CSP response (Appendix A) and FedRamp Tailored Details (appendix A)?

As written in the FedRAMP Tailored policy document (https://tailored.fedramp.gov/policy/) , to be considered FedRAMP Tailored, the answer to all the following questions must be "yes":

1. Does the service operate in the cloud?

2. Is the cloud service fully functional?

3. Is the cloud service a Software-as-a-Service (SaaS), rather than Infrastructure-as-a-Service (IaaS) or Platform-as-a-Service (PaaS)?

4. Does the cloud service provide services without requiring the collection of personally identifiable information (PII)?

5. Is the cloud service low-security-impact, according to the FIPS 199 definition?

6. Is the cloud service hosted within a FedRAMP Authorized infrastructure?

From a Privacy perspective:

*PII (or lack thereof) is already being considered in that one of the required questions is "Does the cloud service provide services without requiring the collection of personally identifiable information (PII)?" A service cannot be considered FedRAMP Tailored if the answer to this question is "no".

*While FedRAMP may do a good job of addressing the Security Controls, its processes and procedures do not appear to give the same consideration and depth to the Privacy Controls (e.g., under the Risk Management Framework, NIST 800-53, Rev. 4, etc.).

Please feel free to reach out if you have any questions!

- Elisabeth Nguyen

**Comment by FedRAMP** [comment]
Thank you for your feedback. The FedRAMP Low baseline applies to all cloud systems seeking authorization for FIPS-199 Low sensitivity. This includes SaaS, PaaS and IaaS; and includes all appropriate NIST 800-53, Rev 4 controls regardless of whether they are implemented by the CSP, underlying service provider, or the government.

FedRAMP Tailored is strictly for SaaS implementations residing on an existing PaaS or IaaS. Further, tailored identifies those controls that are typically inherited form the underlying provider and those typically implemented by the government, allowing the CSP for the LI-SaaS to focus only on those controls related to their system. FedRAMP Tailored also prioritizes this subset of controls. While all are still required, only the most critical are assessed.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
