### ISSUE TITLE
Policy v2 - It's unclear what "the entire cloud stack" means

### ISSUE THREAD

**Issue by thecapacity** [GSA/fedramp-tailored#145]
Note, version 2 of the proposed policy has the following language; "If the LI-SaaS provider is providing the entire cloud stack, we may accept other certifications on a case-by-case basis, such as ISO-27001 or SOC 2, Type 2."

It's not clear to me what "the entire cloud stack" might entail - e.g. if a SaaS provider manages hardware, operating systems, and software, is that "the entire stack" if they're resident in a commercial (COLO) data center?

**Comment by thecapacity** [comment]
From PR: https://github.com/GSA/fedramp-tailored/pull/144/files

**Comment by FedRAMP** [comment]
Thank you for your comment. The documentation has been updated to remove this terminology and clarify the true intention of the statement.

**Comment by thecapacity** [comment]
Looks like the new language is: `... or, where the CSP is also providing the underlying cloud infrastructure and has undergone a recognized independent audit, such as required for a Federal ATO or to obtain an ISO 27001 certificate, PCI or SOC 2, Type 2 assessment.`

Which I think provides a lot more clarity, thanks!
