### ISSUE TITLE
Acceptance of alternative template formats

### ISSUE THREAD

**Issue by anweiss** [GSA/fedramp-tailored#157]
Is the Word doc template for Tailored published under [Appendix B](https://tailored.fedramp.gov/appendices/#appendix-b---fedramp-tailored-mandatory-templates) the only accepted format? If all of the required information as outlined by this template is delivered via an alternative format (e.g. GitBook, web pages, etc), would that be acceptable? If not, would the submission of the content in an alternative format, in addition to the Word doc, be acceptable?

**Comment by thecapacity** [comment]
👋  Hi @anweiss thanks for the question - we're trying to figure that out right now!!

i.e. currently Word/Excel are the official formats, but it didn't make sense to try to recreate the tables in Markdown for the webpage, so we created `.csv` files to leverage GitHub's native viewer.

**Comment by thecapacity** [comment]
Right now we don't have the capability for an alternate submission (e.g. web harvesting) but I'd love to hear your thoughts on how we might do that

**Comment by anweiss** [comment]
Awesome! Thinking in terms of OpenControl, OSCAL, 3rd-party tooling, CSP's own tools, etc, etc that are used to create the alternatively-formatted document and then publishing it to whatever platform is deemed appropriate for distribution when an agency submits a package access request.

**Comment by thecapacity** [comment]
@anweiss yea - what I'd really like to be able to do is;

1. Generate "official templates" internally to the PMO - i.e. for better/worse right now Gov still needs Excel/Word/PDF style outputs for review

2. Create some sort of "generic" <input> mechanism - e.g. "send a completed copy of this CSV to the following URL via POST and we will automatically do `1` on your behalf" --- _like a modern day fax-machine_

Then figure out how to iterate `1+2` together to get `v 3++`

What do you think?

**Comment by anweiss** [comment]
I like it! I think it's a good start, at least until the various tools, formats, specs, etc out in the open mature.

**Comment by JJediny** [comment]
reference: https://github.com/18F/fedramp-dashboard/issues/72
