### ISSUE TITLE
508 issues for https://tailored.fedramp.gov/

### ISSUE THREAD

**Issue by nickbristow** [GSA/fedramp-tailored#17]
## https://tailored.fedramp.gov/
- [x] The links in the footer need more contrast, needs to be 4.5:1
- [x] Skip navigation link doesn't function properly

## https://tailored.fedramp.gov/glossary/
- [ ] Table column headers need `scope='col'` and row headers need `scope='row'`
Also, first cell should be `th` in each row
- [ ] Providing a table caption, even just for screen readers is a nice to have, especially on pages with multiple tables

## https://tailored.fedramp.gov/policy/
- [ ] Tables need proper marker, see notes about glossary table

## https://tailored.fedramp.gov/appendices/
- [ ] Tables need proper marker, see notes about glossary table

**Comment by thecapacity** [comment]
This was helpful for me to learn more about table scope; https://www.w3.org/TR/WCAG20-TECHS/H63.html

**Comment by thecapacity** [comment]
@nickbristow what did you mean by `Skip navigation link doesn't function properly` ? Is that a screen-reader thing? (i.e. browsing the links seemed to work ok for me)

**Comment by thecapacity** [comment]
For the table generation tweaks - it doesn't look like that's something "site specific" - i.e. the tables are in markdown, so the markdown to html conversion is happen through some magic I'm ill equipped to track

**Comment by thecapacity** [comment]
Broaching the table discussion here; https://gsa-tts.slack.com/archives/federalist-support/p1487211643000240

**Comment by nickbristow** [comment]
@thecapacity so if you navigate by tabbing, the first link is a skip navigation button, this should place your focus after the navigation links and onto the main content. Doesn't look like their is content tagged as main content, so it sends you to the start of the page.

**Comment by thecapacity** [comment]
PR for glossary fix; https://github.com/GSA/fedramp-tailored/pull/20

**Comment by thecapacity** [comment]
@nickbristow So do we need to insert a "skip navigation button" UI element or is this a matter of tagging the "{content}" section w/ a class or attribute so tabbing works ?

**Comment by nickbristow** [comment]
@thecapacity nah, you already have the skip nav in there its just not hooked up right. 

https://pages.18f.gov/accessibility/links/

**Comment by thecapacity** [comment]
SkipNav Fix; https://github.com/GSA/fedramp-tailored/pull/22
