### ISSUE TITLE
Section 3.1 FedRAMP Tailored LI-SaaS acceptance questions

### ISSUE THREAD

**Issue by rhoesing** [GSA/fedramp-tailored#171]
Please leave comments and have discussions here related to the acceptance questions.

Excerpt from Section 3.1:
To be considered a FedRAMP Tailored LI-SaaS cloud service, the answer to all the following questions must be “yes:”

1. Does the service operate in a cloud environment?
2. Is the cloud service fully operational?
3. Is the cloud service a Software as a Service (SaaS), as defined by NIST SP 800-145, The NIST Definition of Cloud Computing?
4. The cloud service does not contain personally identifiable information (PII), except as needed to provide a login capability (username, password and email address)?
5. Is the cloud service low-security-impact, as defined by FIPS PUB 199, Standards for Security Categorization of Federal Information and Information Systems?
6. Is the cloud service hosted within a FedRAMP-authorized infrastructure?

**Comment by jbjonesjr** [comment]
Potential discrepancies with elsewhere in the policy:

6. > Is the cloud service hosted within a FedRAMP-authorized infrastructure?

Policy.md allows for:
> SaaS systems are allowed either where the CSP is leveraging ... **or,** where the CSP is also providing the underlying cloud infrastructure and has undergone a recognized independent audit, ...

For clarity, I would update question 6 to make clear that there is an additional caveat in that question.

**Comment by FedRAMP** [comment]
Thank you for your feedback. We have updated these sections to provide more clarity and consistency regarding accepting hosting circumstances.
