### ISSUE TITLE
Inconsistency between FedRAMP Tailored Policy (site) and Template

### ISSUE THREAD

**Issue by virtix** [GSA/fedramp-tailored#187]
First off, nice job on the tailored process and congrats on the launch! 🥇 

The criteria for consideration in the [policy](https://tailored.fedramp.gov/policy/) on https://tailored.fedramp.gov and in the associated [template](https://s3.amazonaws.com/sitesusa/wp-content/uploads/sites/482/2016/04/FedRAMP-Tailored-LI-SaaS-Requirements-2017-08-24-v3.1.docx) item ```6.``` is worded differently.  The language in the template is ambiguous but the policy seems clear. 

### In the Policy
https://tailored.fedramp.gov/policy/

> To be considered a FedRAMP Tailored LI-SaaS cloud service, the answer to all of the following questions must be "yes":

> ...
> 6. Is the cloud service hosted within a FedRAMP authorized infrastructure?

### In the Template

https://s3.amazonaws.com/sitesusa/wp-content/uploads/sites/482/2016/04/FedRAMP-Tailored-LI-SaaS-Requirements-2017-08-24-v3.1.docx

> To be considered a FedRAMP Tailored LI-SaaS cloud service, the answer to all the following questions must be “yes:”
> ...
> 6. Is the cloud service hosted within a FedRAMP-authorized Platform as a Service (PaaS) or
> Infrastructure as a Service (IaaS), or is the CSP providing the underlying cloud infrastructure?

**Comment by rhoesing** [comment]
@virtix Thanks for pointing this out to us.  This was missed when we made updates to policy.md.  I have went ahead and updated the Policy to reflect what was in the Policy Doc listed on fedramp.gov.
