### ISSUE TITLE
FedRAMP Tailored

### ISSUE THREAD

**Issue by marilynhays** [GSA/fedramp-tailored#29]
I found the textual version of Appendix A really confusing. The spreadsheet was easier to understand, because I was able to click back and forth between similar views. 
Perhaps a bit more introductory material about what in in the table - more closely associated with the beginning of the table itself, would help clear this up.

**Comment by FedRAMP** [comment]
Thank you for your comment. Appendix A was published to the web site for review; however, the final version of Appendix A is a spreadsheet that is easier to follow. Please see the second tab in APPENDIX A - FedRAMP Tailored Security Controls Baseline.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
