### ISSUE TITLE
Re-baselined cost estimates to include Tailored

### ISSUE THREAD

**Issue by anweiss** [GSA/fedramp-tailored#31]
It would be great if the current FedRAMP cost estimates could be updated to encompass FedRAMP Tailored -> https://www.fedramp.gov/how-much-does-it-cost-to-go-through-fedramp/.

**Comment by konklone** [comment]
That will take some time, since this is still non-final and no FedRAMP Tailored P-ATOs have been granted. :)

**Comment by FedRAMP** [comment]
Thank you for your comment. Our intention is to gather and publish cost estimates as we have systems use FedRAMP Tailored.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
