### ISSUE TITLE
 Mandatory Templates?

### ISSUE THREAD

**Issue by arleenzank** [GSA/fedramp-tailored#32]
Evaluating the list of controls without the mandatory templates makes it difficult to assess the potential benefit of the Tailored program.  

It is also unclear what FedRAMP will be doing to accelerate the process of making more SaaS products available other than provided by major Cloud providers.  It is our understanding that there is already a significant backlog of packages awaiting JAB approval.  How will this impact that queue?

**Comment by FedRAMP** [comment]
Thank you for your feedback. FedRAMP Tailored is for FedRAMP Agency ATOs, not JAB P-ATOs, thus does not undergo a full JAB review. Further, there is currently no JAB backlog. That was resolved in 2016 as a result of FedRAMP Accelerated. 

We are making the remaining appendicies and teplates available for another round of public review and comment. This complete set of documentation will help add clarity. We welcome additional feedback following that publication.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
