### ISSUE TITLE
What does "low-security-impact" mean?

### ISSUE THREAD

**Issue by cherrypj** [GSA/fedramp-tailored#33]
What *is* the definition of "low-security-impact" (according to the FIPS 199 definition)?

**Comment by FedRAMP** [comment]
Thank you for your question. For the definition of low security impact, please see FIPS PUB 199 here: http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.199.pdf

Section 3, especially Table 1, provides the definitions. Low impact results in *limited* adverse effect on organizational operations, assets, or individuals.

Moderate impact results in *serious* adverse effect on organizational operations, assets, or individuals.
High impact results in *severe or catastrophic* adverse effect on organizational operations, assets, or individuals.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
