### ISSUE TITLE
Impact on Hosted Solutions

### ISSUE THREAD

**Issue by dbhymes** [GSA/fedramp-tailored#34]
How does FedRAMP overlay applications that are FULLY hosted in a private cloud data center?

**Comment by FedRAMP** [comment]
Thank you for your comment. FedRAMP's mission is to authorize a system once and maximize re-use of that authorization among agencies. Systems deployed in a private cloud prohibit re-use, thus do not qualify for a FedRAMP authorization. Of course, an agency or CSP is still free to use FedRAMP's requirements in this scenario as a template.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
