### ISSUE TITLE
Comment - Fedramp tailored

### ISSUE THREAD

**Issue by pamcarpenterva** [GSA/fedramp-tailored#36]
[FedRamp Tailored Program – Comment.pdf](https://github.com/GSA/fedramp-tailored/files/807222/FedRamp.Tailored.Program.Comment.pdf)

**Comment by konklone** [comment]
For the benefit of folks watching this repo by email, here's the text of @pamcarpenterva's uploaded comment:

> FedRamp Tailored Program – Comment
> 
> Thank you for providing the opportunity to provide comments to the proposed FedRamp
> Tailored Program.
> 
> Adobe is very in favor of establishing the FedRamp Tailored Program. We believe it would allow government agencies to acquire and use best in breed solutions while at the same time maintaining acceptable security levels.
> 
> We would recommend establishing 3 tiers within the FedRamp program for cloud solution providers.
> 
> #1 – FedRamp Approval is required due to the use of sensitive information within the Cloud.
> 
> #2 – Govt data is being transmitted and utilized in the cloud but it is not sensitive information.
> 
> #3 – There is a class of cloud services in this category which would never require FedRAMP or FedRAMP Tailored. The FedRamp PMO should give specific guidance on when and when not to use FedRAMP, FedRAMP tailored, and when to do nothing.
> 
> We suggest that #2 and part of #3 above would fall under the FedRamp Tailored program and they would not require full FedRamp Compliance. As stated above in #3 there are cloud based applications that utilize social channels which cannot be FedRamp authorized and which do not store sensitive or private information. These applications would not require any level of FedRamp authorization.
> 
> We would suggest that the FedRamp office allow solution providers to self identify based on the criteria/requirements stated by the FedRamp Tailored Program.
> 
> We would be glad to provide more detail and would welcome the opportunity to discuss this in more detail with the FedRamp Program office.

**Comment by FedRAMP** [comment]
Thank you for your suggestions. The current state of FedRAMP authorizations is based on extensive interaction with Federal agencies, cloud service providers, 3PAOs, and several industry interest groups. Implementing this suggestion requires lawmakers to agree on a fundamental shift in the FedRAMP's role, and all stakeholders to agree the benefits are worth the shift. We are escalating this suggestion with the FedRAMP PMO and among the JAB leadership for feedback and further consideration.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
