### ISSUE TITLE
Criterion 3. Is the cloud service a Software-as-a-Service (SaaS) . . .  Distinguish SaaS from XaaS

### ISSUE THREAD

**Issue by MartinFSmith** [GSA/fedramp-tailored#44]
Are services that support other "end-user" services SaaS?  Or IaaS? or ?? 

Examples: An authentication service (like the former Connect.gov); or a reliable-messaging service. 

Would these qualify for FedRAMP Tailored? (If not, what's the rationale for excluding them?) 

SUGGEST:  Add some clarifying language or, better yet, some examples, of what would qualify what and what would not qualify as "SaaS."

**Comment by FedRAMP** [comment]
Thank you for your question. For now, FedRAMP Tailored is only for LI-SaaS. Non-SaaS systems would not qualify. After demonstrating success with FedRAMP Tailored, we will consider a similar approach could be expanded to include other system types and sensitivity levels based on the success of Tailored. As for specific applications, we would need to evaluate them on a case-by-case basis. A stand-alone messaging SaaS is likely to qualify, an authentication service would likely not qualify; however, FedRAMP would need to understand details about each system before a definitive qualification decision could be rendered.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
