### ISSUE TITLE
Comments from: info@fedramp.gov

### ISSUE THREAD

**Issue by rhoesing** [GSA/fedramp-tailored#47]
The Social Security Administration’s Office of Information Security appreciates the opportunity to review and comment on the new FedRAMP tailored control baseline for Low Impact SaaS cloud solutions. In general, we believe this will provide agencies with an extremely useful tool for authorizing the use of cloud-based solutions deemed to be low impact based on FIPS 199. Like many other federal agencies, SSA has found it challenging as well as resource and time-intensive to apply the FedRAMP control baselines to relatively low-risk cloud solutions. Vendors of these solutions are typically unfamiliar with FedRAMP requirements and/or ill-prepared to navigate the FedRAMP provisional authorization process. Additionally, this approach will likely increase federal agencies’ options and have a positive effect on the competitive procurement process.

Finally, we have reviewed Appendix A, FedRAMP Tailored-CSP Response and are pleased to provide the following detailed recommendations:

· Item 22, Au-9 - recommend upgrading from Attestation to Required

· Item 24, AU-11 – recommend upgrading from NSO to Attestation

· Item 35, CM-2 – recommend upgrading from Attestation to Required

· Item 47, CP-10 – recommend upgrading from NSO to FED/Conditional

· Item 58, IA-8 - recommend upgrading from Attestation to FED/Conditional

· Item 123, SI-3 – recommend allowing this to be either Required or Inherited

· Item 124, SI-4 - recommend allowing this to be either Required or Inherited

For questions or additional information please contact Jennifer.Rutz@ssa.gov

Tim May

Deputy Associate Commissioner 
Office of Information Security

Office of Systems

Social Security Administration

**Comment by FedRAMP** [comment]
Thank you for your feedback. After careful consideration, we are electing to keep the existing requirements characterization in Appendix A (attested, NSO, etc.). We will monitor systems using FedRAMP Tailored to determine if we need to adjust any of these.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
