### ISSUE TITLE
PII, PIAs, Re-use of SSPs, and the SaaS/Social Media/3rd Party App Distinction

### ISSUE THREAD

**Issue by thorsteve** [GSA/fedramp-tailored#48]
I'm submitting this feedback as someone who is familiar with FedRAMP and participated in a number of cloud initiatives across multiple agencies. These don't reflect an agency official response.

The good:

- Overall should be a good step forward for niche/specialized SaaS providers and for small business SaaS providers (assuming they use a FedRAMP-authorized IaaS provider on the back-end). This is where the most value from cloud computing is likely to accrue. So, I'm happy to see it come to fruition. The extensive FedRAMP process has been a significant barrier to small, high-value players. I've observed this to be the case in: project management, team collaboration, agile tools, lab management, employee communications tools, medical services (non-PHI/PII), and a number of other areas.
- Requires SaaS provider to clearly delineate control inheritance from FedRAMP IaaS provider versus government customer responsibility versus SaaS provider control implementation. This should make it easier for (a) the agency to assess the SSPs and security controls and (b) plan for implementation of agency-supported security controls from a project management and solution design perspective. For example AWS published at the government's request a clear list of what the customer is responsible for versus AWS, which has made it easier for agencies to plan their cloud deployments with the provider.
- Assessments of FISMA-Low SaaS providers can be done by agency security teams rather than 3PAOs. That should represent a significant time/cost savings for the agencies and/or SaaS service providers - especially the small business / niche players.
- A number of the controls contain CSP self-attestation, which should further expedite the process.

GSA needs to clarify the following:

- Need more specificity in the policy on the type of PII that is prohibited (federal employee versus private citizen, sensitive versus non-sensitive, identifiable form versus not in identifiable form, etc.). This distinction between the different types of PII is critical for system categorization and ultimately what would be in-scope or out-of-scope of the tailored process.
- It feels like there should be more guidance on privacy and PIAs – even for Low systems that only store non-sensitive, federal employee data.
- Not clear how the FedRAMP program and GSA will interface with Agencies to publish agency-developed cloud authorization packages (potential re-use of SSPs as supported in the original approach to FedRAMP). This is cited as a benefit, but the process isn’t described.
- As a long-standing issue, it would be helpful to have better guidance on the distinctions between SaaS, social media, and third party hosted apps so that security requirements are clearer - given that different security/privacy requirements exist for each of these domains.
- The following guidance is not complete or ready for comment:
     - “Mandatory” provider templates.
     - Tailored test cases.
     - Tailored continuous monitoring requirements.

**Comment by FedRAMP** [comment]
Thank you for your comment. There was overwhelming feedback regarding a threshold for PII. We have defined a PII allowance for systems that collect only enough PII to provide a login capability. While FedRAMP is asserting a system may be considered low with only this threshold of PII, each agency's AO will always have the final decision.

Also, all sections are now complete and part of the update we are publishing for the next round of public comment.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
