### ISSUE TITLE
Basecamp

### ISSUE THREAD

**Issue by riemino** [GSA/fedramp-tailored#53]
I have a question about how future FedRAMP streamline process will allow SaaS providers, such as Basecamp, to be able to get FedRAMP approved.  Seems like Basecamp was not interested in the FedRAMP approval process because of limitations that this might have on their future feature development workflow.

**Comment by FedRAMP** [comment]
Thank you for your question. While we are unable to speak for the motivations of any specific vendor, if Basecamp qualifies for FedRAMP Tailored, this would reduce their cost to achieve an ATO, and potentially enable that ATO to be leveraged by other agencies.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
