### ISSUE TITLE
Test for Comment-a-thon: Mint Chocolate Chip Ice Cream is the Best

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#56]
I really like mint chocolate chip ice cream because it tastes good and pairs nicely with other flavors.

**Comment by hansmanzke** [comment]
@zareesinger Strawberry obvs!

**Comment by theresa-west** [comment]
@zareesinger @hansmanzke Obviously, vanilla is the best! Classic flavor that goes great with pie and cake.

**Comment by zareesinger** [comment]
@hansmanzke I'd love to learn more about why you disagree with my obviously right opinion and think it is appropriate for fruit and ice cream to be mixed in a DESSERT.

**Comment by hansmanzke** [comment]
@zareesinger Thumbs down to your thumbs down. Theresa, I can't seem to @ you, but vanilla is indeed a noble and mighty flavor on its own, especially natural vanilla bean.

**Comment by ctjacks5** [comment]
- @zareesinger  If I wanted mint for dessert, I'd just brush my teeth. 
- @hansmanzke  Strawberry? The flavor everyone leaves behind in Neapolitan?
-  @theresa-west  I have neutral feelings on Vanilla, much like its taste.

Cookies and Cream reigns supreme. It's two desserts in one. I believe we can close this issue once and for all.

**Comment by katielotterman** [comment]
@ctjacks5 you're too good

**Comment by zareesinger** [comment]
@ctjacks5 yep fine you win.

**Comment by JohnWHamilton** [comment]
I dunno...strawberry is def. my fav.

**Comment by secureCloudio** [comment]
vanilla

**Comment by skaczmar** [comment]
I never realized there were any other flavors beside chocolate.  What will they think of next?

**Comment by rhoesing** [comment]
@zareesinger Chocolate chip cookie doughhhhh

**Comment by ssanborn** [comment]
Chocolate

**Comment by ultrashea** [comment]
Y'all are wrong - Rum Raisin or nothing!

**Comment by FedRAMP** [comment]
We found no actionable comments here. Thank you for your participation.
