### ISSUE TITLE
Appendix B - Mandatory Templates

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#60]

**Comment by aframpton** [comment]
When will the Tailored Assessment Test cases be released?

**Comment by FedRAMP** [comment]
Thank you for your question. There will be no separate FedRAMP Tailored test cases. FedRAMP has already published the test cases for a low baseline system. While the number of controls requiring assessment is reduced, the actual test for those controls remains the same as for the low baseline. Please visit the Templates area of fedramp.gov and download the SAP APPENDIX A - FedRAMP Low Security Test Case Procedures Template.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
