### ISSUE TITLE
Tailoring Action: Inherited - Controls FedRAMP determined to be inherited from the underlying infrastructure provider (i.e., FedRAMP authorized IaaS/PaaS) for Low Impact Cloud SaaS

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#62]

**Comment by collabarchitect** [comment]
Inherited Controls should be accepted and incorporated into the FedRAMP Tailored documentation. Typically, these inherited controls are non-technical in nature (e.g. NIST Control Family AT, MA, PE, etc.) and therefore most systems would not address these types of controls. Bottom Line: CSP inherited controls would be 'accepted' provided validation could be assessed (via re-certification by Original Authorizing Official)

**Comment by FedRAMP** [comment]
Thank you for your suggestion. At this time, we are trying to streamline the approach for low risk systems while focusing on the most critical security controls. We will re-evaluate this approach after a few systems have come through the FedRAMP Tailored process.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
