### ISSUE TITLE
Step 6 - Monitor Security Controls

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#67]

**Comment by eric2525** [comment]
Does a FedRAMP Tailored have the same ConMon deliverables for the Agency using the Continuous Monitoring requirements?

**Comment by FedRAMP** [comment]
Thank you for your question. The frequency is similar; however, the CSP has more latitude with reporting details. Please see APPENDIX D - FedRAMP Tailored LI-SaaS Continuous Monitoring Guide for more information.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
