### ISSUE TITLE
Step 5 - Authorize Information System

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#68]

**Comment by stephenjcaruso** [comment]
once approved, what are the specific steps required for FedRAMP authorizations for LISaaS to be leveraged by other agencies? will the process for post-authorization use be the same as it is today? if so, will this be agile enough?

**Comment by druboi31779** [comment]
Under step 5, "Authorize", it states that in the ATO letter the "Identification of the residual risks that were accepted by the AO in issuing the ATO" are included (#4). It would seem that potentially a count of issues or risks accepted and the severity of those risks would be more realistic (dependent on the size and complexity of the system). The details of the residual risk(s) would be captured in the SAR (or other assessment post-mortem document) and the ATO letter would refer to it...

**Comment by FedRAMP** [comment]
Thank you for your question. The steps for other agencies to leverage a FedRAMP Tailored authorization are the same as for a Moderate FedRAMP Agency ATO. The other agencies request access to the secure repository via info@fedramp.gov, then review the system's security documentation. The leveraging agency's AO then decides whether to accept the existing documentation, conduct a separate assessment, or decline to authorize the system.

Regarding residual risks in the ATO letter, we are attempting to provide a single summary that makes it easier for leveraging agencies to consider whether to dig deeper into the existing FedRAMP Tailored assessment or take a different course of action. If we find inclusion of this information here presents problems, we will re-evaluate how that information is communicated

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
