### ISSUE TITLE
Step 4 - Assess Security Controls

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#69]

**Comment by rgaitonde** [comment]
How are you able to ensure that the controls are properly implemented by the CSP without a 3PAO validating the information?

**Comment by JBitzer** [comment]
one of the issues I find with software solutions is the cost of the 3PAO  - the investment that they must make to have a 3PAO for the Moderate level.  perhaps there's a way to have a lower cost whether the fees charged by a current 3PAO provider or perhaps this could be something even targeted specifically for new companies/**small businesses** entries to the assessment/validation role.

**Comment by FedRAMP** [comment]
Thank you for your question. As with any FedRAMP Agency ATO, the use of a Third Party Assessment Organization (3PAO) is recommended, but not required. An assessment must still be performed, and the Agency's AO must ensure the assessment is conducted properly by a trusted team; however, the Agency's AO has ultimate discretion on this.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
