### ISSUE TITLE
Step 3 - Implement Security Controls

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#70]

**Comment by aframpton** [comment]
"The CSP is require to complete the templates; however, an agency may also assist the CSP in completing the documents." This needs further clarification. There should be no reason for an agency to help the CSP complete their security documentation. The CSP should know their system's capabilities are and what the customer responsibilities should be. Additionally, if the agency is actively helping the CSP write its documentation, issues of conflict of interest may arise when it comes to objectively accepting any risks presented in the security package.

**Comment by FedRAMP** [comment]
Thank you for your feedback. This is sometimes necessary to ensure accuracy. It is not viewed as a conflict of interest as sometimes agencies build systems in-house and complete all the security documentation. It is the agency AO's responsibility to ensure the system is properly secure before authorizing it regardless of who completes the documentation. Further, some requirements must be addressed by the agency and must be included in the security documentation, thus the CSP would require agency assistance for those requirements.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
