### ISSUE TITLE
Required (Conditional) Control: No. 102, SC-13, Conditional Cryptographic Protection 

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#74]

**Comment by JTRFedRAMPHHS** [comment]
SC-13 is still part of the low baseline. I do not think it should be conditional.

https://nvd.nist.gov/800-53/Rev4/control/SC-13

**Comment by JTRFedRAMPHHS** [comment]
On a True L,L,L system we may be willing to allow FIPS 140-2Compliant encryption rather than Validated modules.

**Comment by FedRAMP** [comment]
Thank you for your suggestion. For now we are relaxing this requirement given FedRAMP Tailored is targeting only low risk SaaS systems. We are, however, requiring the CSPs to document what cryptography they are using with the intention of evaluating existing modules within the context of the system's actual function.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
