### ISSUE TITLE
Required Control: No. 101, SC-12, Cryptographic Key Establishment and Management

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#75]

**Comment by ABUBSHAIT** [comment]
How does this security control relate to FIPS 140-2. My understanding is that getting a FedRAMP authorization a CSP must have a FIPS 140-2 validation. Are these tested desperately ? or is using a pre-validated module to handle cryptographic functionality sufficient?

**Comment by FedRAMP** [comment]
Thank you for your comment. The use of FIPS 140-2 validated or NSA-approved cryptographic algorithms is a Federal requirement. Most CSPs elect to use FIPS-140-2 validated modules. The correct module name, version number, and certificate number must be specified in the control documentation. The assessor typically validates the accuracy of this information. FedRAMP typically verifies that the certificate number matches the specified module name and version number.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
