### ISSUE TITLE
Required Control: No. 90, RA-5, Vulnerability Scanning

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#79]

**Comment by rgaitonde** [comment]
without requiring the scanner to be updated it's unclear if the scanner will be effective. 

RA-5 (1)	Vulnerability Scanning | Update Tool Capability
RA-5 (2)	Vulnerability Scanning | Update by Frequency / Prior to New Scan / When Identified
RA-5 (3)	Vulnerability Scanning | Breadth / Depth of Coverage
RA-5 (5)	Vulnerability Scanning | Privileged Access
RA-5 (6)	Vulnerability Scanning | Automated Trend Analyses
RA-5 (8)	Vulnerability Scanning | Review Historic Audit Logs

**Comment by FedRAMP** [comment]
Thank you for your suggestion. We used the NIST SP 800-53 Revision 4 baseline for low systems as a
 starting point. RA-(1) and RA-5(2) are not specified by NIST for low systems. There are many controls excluded by NIST for low. We are electing to follow that baseline unless we are presented with a compelling reason to add a non-low requirement for low systems. An AO always has the latitude to add this or any requirement as appropriate. In this case, we are evaluating the inclusion of a statement to address this in APPENDIX D - FedRAMP Tailored LI-SaaS Continuous Monitoring Guide, but will continue to strictly follow the NIST baseline.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
