### ISSUE TITLE
Required Control: No. 81, PS-3, Personnel Screening

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#82]

**Comment by badorward** [comment]
Several CSPs have asked about the requirement for US citizens. The FedRAMP baselines do not require US citizens, but many agencies do.  CSPs are free to define their own background investigation requirements, consistent with PS-3 and PS-3 (3); however, agencies are likely to require at least a NACI.

**Comment by FedRAMP** [comment]
Thank you for your comment. It does a great job summarizing FedRAMP's position on citizenship.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
