### ISSUE TITLE
Required Control: No. 55, IR-6, Incident Reporting

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#84]

**Comment by rgaitonde** [comment]
Based upon the controls required the following should be added:

IR-3	Incident Response Testing
IR-3 (2)	Incident Response Testing | Coordination with Related Plans
IR-4 (1)	Incident Handling | Automated Incident Handling Processes
IR-7 (2)	Incident Response Assistance | Coordination With External Providers
IR-9 (1)	Information Spillage Response | Responsible Personnel
IR-9 (2)	Information Spillage Response | Training

**Comment by FedRAMP** [comment]
Thank you for your suggestion. We used the NIST SP 800-53 Revision 4 baseline for low systems as a
 starting point. None of the controls you listed are specified by NIST for low systems. There are many controls excluded by NIST for low systems. We are electing to follow this baseline unless we are presented with a compelling reason to add a non-low requirement for low systems. An AO always has the latitude to add this or any requirement as appropriate.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
