### ISSUE TITLE
Required (Conditional) Control: No. 47, IA-8 (1), Identification and Authentication (Non Organizational Users)

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#87]

**Comment by Wynsome** [comment]
Since Non-organizational users can be CSP internal users assigned to a Federal Agency I believe this control should be Mandatory

**Comment by FedRAMP** [comment]
Thank you for your suggestion. This control is mandatory for privileged user accounts. We are relaxing it for non-privileged user accounts.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
