### ISSUE TITLE
Required (Conditional) Control: No. 39, IA-2 (12), Identification and Authentication (Organizational Users)

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#90]

**Comment by alinsFedRAMP** [comment]
Does this mean that offerings must ONLY support PIV, or can other authentication mechanisms be used? Can other mechanisms be used for CSP staff that cannot acquire PIV credentials?

**Comment by FedRAMPPMO** [comment]
Thank you for your comment. The focus of IA-2(1) is to ensure privileged account use multi-factor authentication when accessing the system. FedRAMP interprets this to mean any mechanism by which a privileged account is used, including network and remote access.

**Comment by FedRAMP** [comment]
Thank you for your question. No, the requirement is for the system to have the ability to accept Common Access Card/Personal Identity Verification (CAC/PIV) for agencies requiring it. Unless required by a specific agency, other forms of authentication are acceptable, including other forms of multi-factor authentication for privileged user accounts.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
