### ISSUE TITLE
Required Control: No. 38, IA-2 (1), Identification and Authentication (Organizational Users)

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#91]

**Comment by alinsFedRAMP** [comment]
Does this mean that offerings must ONLY support PIV, or can other authentication mechanisms be used? Can other mechanisms be used for CSP staff that cannot acquire PIV credentials?

**Comment by badorward** [comment]
Since, IA-2(11) is not a required FedRAMP Tailored control, should CSPs assume that "network access" includes remote access (access through an external network)?

**Comment by FedRAMP** [comment]
Thank you for your comment. The focus of IA-2(1) is to ensure privileged account use multi-factor authentication when accessing the system. FedRAMP interprets this to mean any mechanism by which a privileged account is used, including network and remote access.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
