### ISSUE TITLE
Required Control: No. 31, CM-6, Configuration Settings

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#94]

**Comment by arcbeckman** [comment]
Incorporate automation into configuration settings

**Comment by collabarchitect** [comment]
Consider pursuing a similar approach as Jason Hess: https://fcw.com/articles/2017/03/21/nga-24-hour-cloud.aspx  Cloud is inherently dynamic!  Using static security methodologies / processes to monitor a system hosted on Cloud will ultimately fail. As NGA Developers are creating Applications, the Security Scans are being outputted into an automated System Security Plan (leveraging YAML). CM-6 could be adapted using a Control Enhancement to encourage both System Owners and Vendors to adapt automated / dynamic security processes.

**Comment by FedRAMP** [comment]
Thank you for your suggestions. These are great goals and are consistent with DHS Continuous Diagnostics and Mitigation CDM goals; however, we do not currently require automation of moderate systems. The goal of FedRAMP Tailored is to streamline security for low-risk systems. These requirements contradict that goal. As CDM tools mature for more sensitive systems, we will evaluate an appropriate time to migrate them down to less sensitive systems.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
