### ISSUE TITLE
Required Control: No. 26, CA-7, Continuous Monitoring

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#97]

**Comment by badorward** [comment]
The FedRAMP requirements for this control are 1) monthly vulnerability scans performed by the CSP and 2) annual scans performed by an independent assessor.

For CSPs under FedRAMP Tailored, are monthly scans required? Are CSPs required to undergo an annual assessment that includes 3PAO-run vulnerability scans?

**Comment by FedRAMP** [comment]
Thank you for your question. Yes. Monthly scans and reporting, as well as annual assessments, are still required. We are relaxing the reporting requirements to allow these smaller systems to report with the individual tools they possess.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
