### ISSUE TITLE
Required Control: No. 21, CA-2, Security Assessments

### ISSUE THREAD

**Issue by zareesinger** [GSA/fedramp-tailored#99]

**Comment by JuniperChad** [comment]
How are the security assessments conducted (i.e. are they run internally by the government, through a contractor, or by the CSP)? How do we define security assessment services and if it is met by a contractor/CSP, can the said-incumbent provide solutions, or will it create a conflict of interest?

**Comment by FedRAMP** [comment]
Thank you for your question. Each agency conducts their security assessment individually according to their own resources. An agency ATO will not be granted without a security assessment. As such, this requirement will always be satisfied by the government under the current scope of FedRAMP Tailored systems.

**Comment by cbukovac** [comment]
Closed in preparation for V2 release
